### ISSUE TITLE
Command Not Found

### ISSUE THREAD

**Issue by chaitanyarahalkar** [mxrch/penglab#2]
I uncommented your code in the last code cell. It couldn't run neither hashcat nor john the ripper. 

![image](https://user-images.githubusercontent.com/24942959/84377201-e2e6ad00-abff-11ea-9530-564aadee3f32.png)

**Comment by mxrch** [comment]
Hi, you must have set Hashcat or John to True in the first cell. Then, if you do "Run all" (idk the name in english) it will check the condition and install the tools you have selected.
Check the Readme for the installation instructions.

**Comment by chaitanyarahalkar** [comment]
My bad! Thanks for the prompt response!
