### ISSUE TITLE
How to Load Hashfiles

### ISSUE THREAD

**Issue by Shazgul** [mxrch/penglab#5]
I already understood how to crack Single Hashes with Penglab and Hashcat, but how to crack Hashlists?!

**Comment by mxrch** [comment]
Hello, personnally I like to put this in the last cell : 
```python
hashes = """
<your hash>
<your hash>
<...>
"""
open('target.hash', 'w').write(hashes)
!hashcat -a X -m X target.hash <your wordlist>
```

It was very useful to crack the hashdump of every machine in the OSCP Lab !

**Comment by Shazgul** [comment]
That doesn't really works for me, tried it with around 300 Hashes and just got this Output:

`hashcat (v6.1.1-98-g3dd89bc6) starting...

nvmlDeviceGetFanSpeed(): Not Supported

CUDA API (CUDA 10.1)
====================
* Device #1: Tesla T4, 14969/15079 MB, 40MCU

OpenCL API (OpenCL 1.2 CUDA 10.1.152) - Platform #1 [NVIDIA Corporation]
========================================================================
* Device #2: Tesla T4, skipped

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 27

Generated bitmap tables...tcmalloc: large alloc 1233903616 bytes == 0x558efd9c0000 @  0x7f4e94676615 0x558df7b38a42 0x558df7b3a7c9 0x558df7b3aa13 0x558df7b3b1d7 0x558df7b2ef71 0x558df7b2f79a 0x558df7b2b54c 0x7f4e938a9b97 0x558df7b2b58a
tcmalloc: large alloc 1542381568 bytes == 0x558f4727e000 @  0x7f4e94676615 0x558df7b38a42 0x558df7b3a7c9 0x558df7b3aa13 0x558df7b3b1d7 0x558df7b2ef71 0x558df7b2f79a 0x558df7b2b54c 0x7f4e938a9b97 0x558df7b2b58a
tcmalloc: large alloc 1927979008 bytes == 0x558fa396c000 @  0x7f4e94676615 0x558df7b38a42 0x558df7b3a7c9 0x558df7b3aa13 0x558df7b3b1d7 0x558df7b2ef71 0x558df7b2f79a 0x558df7b2b54c 0x7f4e938a9b97 0x558df7b2b58a
tcmalloc: large alloc 2409979904 bytes == 0x558f06882000 @  0x7f4e94676615 0x558df7b38a42 0x558df7b3a7c9 0x558df7b3aa13 0x558df7b3b1d7 0x558df7b2ef71 0x558df7b2f79a 0x558df7b2b54c 0x7f4e938a9b97 0x558df7b2b58a
tcmalloc: large alloc 3012476928 bytes == 0x559017016000 @  0x7f4e94676615 0x558df7b38a42 0x558df7b3a7c9 0x558df7b3aa13 0x558df7b3b1d7 0x558df7b2ef71 0x558df7b2f79a 0x558df7b2b54c 0x7f4e938a9b97 0x558df7b2b58a
tcmalloc: large alloc 3765600256 bytes == 0x5590cb102000 @  0x7f4e94676615 0x558df7b38a42 0x558df7b3a7c9 0x558df7b3aa13 0x558df7b3b1d7 0x558df7b2ef71 0x558df7b2f79a 0x558df7b2b54c 0x7f4e938a9b97 0x558df7b2b58a
^C`
